path = ../../../3rdparty/SFML-2.5.1
movable:
	g++ ./movable.cpp -std=c++11 -o movable.exe -I $(path)/include -L $(path)/lib/ -lsfml-graphics -lsfml-window -lsfml-system
file:
	g++ ./file.cpp -std=c++11 -o file.exe -I $(path)/include -L $(path)/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
movable1:
	g++ ./movable1.cpp -std=c++11 -o movable1.exe -I $(path)/include -L $(path)/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
