path = ../../../3rdparty/SFML-2.5.1
context_menu:
	g++ ./context_menu.cpp -std=c++11 -o context_menu.exe -I $(path)/include -L $(path)/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
move_and_delete_with_menu:
	g++ ./move_and_delete_with_menu.cpp -std=c++11 -o move_and_delete_with_menu.exe -I $(path)/include -L $(path)/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
move_and_delete_with_menu1:
	g++ ./move_and_delete_with_menu1.cpp -std=c++11 -o move_and_delete_with_menu1.exe -I $(path)/include -L $(path)/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
test:
	g++ ./test.cpp -std=c++11 -o test.exe -I $(path)/include -L $(path)/lib/ -lsfml-graphics -lsfml-window -lsfml-system