balls:
	g++ ./balls.cpp -std=c++11 -o balls.exe -I../../../3rdparty/SFML-2.5.1/include -L ../../../3rdparty/SFML-2.5.1/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
program1_teleportation:
	g++ ./program1_teleportation.cpp -std=c++11 -o program1.exe -I../../../3rdparty/SFML-2.5.1/include -L ../../../3rdparty/SFML-2.5.1/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
program2_reflection:
	g++ ./program2_reflection.cpp -std=c++11 -o program2.exe -I../../../3rdparty/SFML-2.5.1/include -L ../../../3rdparty/SFML-2.5.1/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
program3_gravitation:
	g++ ./program3_gravitation.cpp -std=c++11 -o program3.exe -I../../../3rdparty/SFML-2.5.1/include -L ../../../3rdparty/SFML-2.5.1/lib/ -lsfml-graphics -lsfml-window -lsfml-system 
program4_gravitation_with_weight:
	g++ ./program4_gravitation_with_weight.cpp -std=c++11 -o program4.exe -I../../../3rdparty/SFML-2.5.1/include -L ../../../3rdparty/SFML-2.5.1/lib/ -lsfml-graphics -lsfml-window -lsfml-system
program5_charge:
	g++ ./program5_charge.cpp -std=c++11 -o program5.exe -I../../../3rdparty/SFML-2.5.1/include -L ../../../3rdparty/SFML-2.5.1/lib/ -lsfml-graphics -lsfml-window -lsfml-system
program6_adding_balls:
	g++ ./program6_adding_balls.cpp -std=c++11 -o program6.exe -I../../../3rdparty/SFML-2.5.1/include -L ../../../3rdparty/SFML-2.5.1/lib/ -lsfml-graphics -lsfml-window -lsfml-system
